
export const Routes = {
    // pages
    Presentation: { path: "/" },
    DashboardOverview: { path: "/dashboard/overview" },
    AdminDash: { path: "/dashboard/admin" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    Registerind: { path: "/examples/register" },
    Apply: { path: "/industry/apply" },
    Applications: { path: "/industry/applications" },
    AppEv1: { path: "/industry/appEv1" },
    AppEv2: { path: "/industry/appEv2" },
    Dash_1: { path: "/industry/evaluator1" },
    Dash_2: { path: "/industry/evaluator2" },
    Dash_3: { path: "/industry/evaluator3" },
    EvaluationForm:{path:"/industry/evform/:id"},
    Appfed:{path:"/industry/appfed/:id"},
    AddUser: { path: "/examples/add-user" },
    Addrole: { path: "/examples/add-role" },
    Profile: { path: "/industry/profile" },
    Userdetails: { path: "/examples/user-details" },
    Pass: { path:"/examples/pass" },
    IndDash: { path:"/dashboard/industry" },
    IndustryList:{ path:"/components/industry-list"},
    Adsidebar:{path:"/Industry/sidebar"},
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};